resolver: lts-3.11
packages:
- cep/cep
- confc
- consensus
- consensus-paxos
- distributed-commands
- distributed-process-scheduler
- distributed-process-test
- distributed-process-trans
- halon
- mero-halon
- mero-integration
- network-transport-controlled
- replicated-log
- rpclite
- sspl
# vendor packages
- location:
    git: https://github.com/tweag/distributed-process.git
    commit: c7e4652b5b6f9e1fff93a8768fef2114605b8c10
  extra-dep: true
- location:
    git: https://github.com/haskell-distributed/network-transport-inmemory.git
    commit: f70722138c7de0ceef0872eefca34a6e4437d552
  extra-dep: true
- location:
    git: https://github.com/tweag/network-transport-tcp.git
    commit: cf1cce0baf2b286f33330cf742a1f66de13cc16d
  extra-dep: true
- location: vendor/netwire
  extra-dep: true
- location: vendor/options-schema
  extra-dep: true
- location: vendor/tasty-files
  extra-dep: true

extra-deps:
- aeson-schema-0.4.0.0
- directory-1.2.5.0
- distributed-process-tests-0.4.3.2
- distributed-static-0.3.2.0
- genders-0.1.0.1
- inline-c-0.5.5.1
- leveldb-haskell-0.6.3
- network-transport-tests-0.2.2.0
- rank1dynamic-0.3.1.0
- rematch-0.2.0.0

docker:
  enable: true
  repo: quay.io/tweag/halon:latest
  registry-login: true
  # XXX To route around GHC bug #11042
  env:
  - LD_LIBRARY_PATH=/mero/mero/.libs
  - MERO_ROOT=/mero
  - USER=stack # for m0 script
  - TEST_LISTEN=127.0.0.1:8090

nix:
  enable: false
  packages: [ leveldb
            , libiconv
            , pcre
            ]

extra-include-dirs:
- /mero
- /mero/extra-libs/galois/include
- ../rpclite/rpclite
extra-lib-dirs:
- /mero/mero/.libs
