resolver: lts-5.17
packages:
- cep/cep
- confc
- consensus
- consensus-paxos
- distributed-commands
- distributed-process-scheduler
- distributed-process-test
- distributed-process-trans
- halon
- halon-instances
- mero-halon
- mero-integration
- network-transport-controlled
- replicated-log
- rpclite
- sspl
# vendor packages
- location:
    git: https://github.com/tweag/distributed-static.git
    commit: 0bbb55cfdd6715290828785d4865671660b32edc
  extra-dep: true
- location:
    git: https://github.com/tweag/distributed-process.git
    commit: fd46c615985af2f8d61b44f046f20385b9a0eb42
  extra-dep: true
- location:
    git: https://github.com/haskell-distributed/network-transport-inmemory.git
    commit: f70722138c7de0ceef0872eefca34a6e4437d552
  extra-dep: true
- location:
    git: https://github.com/tweag/network-transport-tcp.git
    commit: dd1369e8ed3af660e46fdaad913e04f8dd34d2cc
  extra-dep: true
- location:
    git: https://github.com/seagate-ssg/options-schema.git
    commit: 20d7e5213c0ff04853f3852ee948795ae81613d4
  extra-dep: true
- location:
    git: https://github.com/seagate-ssg/tasty-files.git
    commit: b800398400b05b5e6cafa8189511c3ec6532958e
  extra-dep: true
- location:
    git: https://github.com/nc6/gitrev.git
    commit: 52f4c1c96c776ca74bf9f9b01808b0c1d5e0ac94
  extra-dep: true

extra-deps:
- directory-1.2.5.0
- distributed-process-tests-0.4.3.2
- genders-0.1.0.1
- rematch-0.2.0.0
- clock-0.7.1
- ghc-datasize-0.1.2
- aeson-schema-0.4.1.1
- aeson-0.11.2.0

docker:
  enable: true
  repo: quay.io/tweag/halon:latest
  registry-login: true
  # XXX To route around GHC bug #11042
  env:
  - LD_LIBRARY_PATH=/mero/mero/.libs
  - MERO_ROOT=/mero
  - USER=stack # for m0 script
  - TEST_LISTEN=127.0.0.1:8090

nix:
  enable: false
  packages: [ leveldb
            , libiconv
            , pcre
            ]
