resolver: lts-8.24
packages:
- cep/cep
- confc
- consensus
- consensus-paxos
- distributed-commands
- distributed-process-scheduler
- distributed-process-test
- distributed-process-trans
- halon
- halon-instances
- mero-halon
- mero-integration
- network-transport-controlled
- replicated-log
- rpclite
- sspl
# vendor packages
- location:
    git: https://github.com/tweag/distributed-process.git
    commit: e53c8357e0dbf932ed3f8dd983a2cda66a509251
  extra-dep: true
- location:
    git: https://github.com/seagate-ssg/options-schema.git
    commit: 9eaf45b3105358ef3c0b2a6169b68225f8f481d6
  extra-dep: true
- location:
    git: https://github.com/seagate-ssg/tasty-files.git
    commit: ab35f545a7ac52168ef1d4c5babbc34942762a85
  extra-dep: true
- location:
    git: https://github.com/nc6/gitrev.git
    commit: 52f4c1c96c776ca74bf9f9b01808b0c1d5e0ac94
  extra-dep: true
- location:
    git: https://github.com/Fuuzetsu/aeson-schema.git
    commit: 04de4b1f3876e5d8010d32a3bde4be7a7ae9d36a
  extra-dep: true

extra-deps:
- distributed-static-0.3.8
- distributed-process-tests-0.4.3.2
- genders-0.1.0.1
- rematch-0.2.0.0
- ghc-datasize-0.1.2
- validation-0.5.4
- QuickCheck-2.8.2
- aeson-0.11.3.0
- shelly-1.6.8.3

docker:
  enable: false
  repo: quay.io/tweag/halon:latest
  registry-login: true
  # XXX To route around GHC bug #11042
  env:
  - LD_LIBRARY_PATH=/mero/mero/.libs
  - MERO_ROOT=/mero
  - USER=stack # for m0 script
  - TEST_LISTEN=127.0.0.1:8090

nix:
  enable: false
  packages: [ leveldb
            , libiconv
            , pcre
            ]

allow-different-user: true
