resolver: lts-3.11
packages:
- cep/cep
- confc
- consensus
- consensus-paxos
- distributed-commands
- distributed-process-scheduler
- distributed-process-test
- distributed-process-trans
- halon
- mero-halon
- network-transport-controlled
- replicated-log
- rpclite
- sspl
# vendor packages
- location: vendor/distributed-process
  extra-dep: true
- location: vendor/netwire
  extra-dep: true
- location: vendor/network-transport-inmemory
  extra-dep: true
- location: vendor/network-transport-tcp
  extra-dep: true
- location: vendor/options-schema
  extra-dep: true
- location: vendor/tasty-files
  extra-dep: true

extra-deps:
- aeson-schema-0.4.0.0
- distributed-process-tests-0.4.3.2
- distributed-static-0.3.2.0
- inline-c-0.5.5.1
- leveldb-haskell-0.6.3
- network-transport-tests-0.2.2.0
- rank1dynamic-0.3.1.0
- rematch-0.2.0.0

docker:
  enable: true
  repo: quay.io/tweag/halon:latest
  registry-login: true
  # XXX To route around GHC bug #11042
  env:
  - LD_LIBRARY_PATH=/mero/mero/.libs
  - MERO_ROOT=/mero
  - USER=stack # for m0 script

extra-include-dirs:
- /mero
- /mero/extra-libs/galois/include
- ../rpclite/rpclite
extra-lib-dirs:
- /mero/mero/.libs
