resolver: lts-9.21
packages:
- cep/cep
- confc
- consensus
- consensus-paxos
- distributed-commands
- distributed-process-scheduler
- distributed-process-test
- distributed-process-trans
- halon
- halon-instances
- mero-halon
- mero-integration
- network-transport-controlled
- replicated-log
- rpclite
- sspl
# vendor packages
- location:
    git: https://github.com/seagate-ssg/options-schema.git
    commit: 9eaf45b3105358ef3c0b2a6169b68225f8f481d6
  extra-dep: true
- location:
    git: https://github.com/seagate-ssg/tasty-files.git
    commit: ab35f545a7ac52168ef1d4c5babbc34942762a85
  extra-dep: true
- location:
    git: https://github.com/seagate-ssg/gitrev.git
    commit: 52f4c1c96c776ca74bf9f9b01808b0c1d5e0ac94
  extra-dep: true

extra-deps:
- aeson-schema-0.4.1.3
- containers-0.5.10.2
- distributed-process-0.7.4
- distributed-process-extras-0.3.5
- distributed-static-0.3.8
- ghc-datasize-0.1.2
- network-transport-0.5.2
- network-transport-tcp-0.6.0

ghc-options:
  # XXX `CEP.regression.fork-remove-messages` UT will fail unless
  # `distributed-process` package is built with `-O0` option;
  # see https://github.com/seagate-ssg/halon/pull/1425#issuecomment-399595953
  #
  # TODO: Find the root cause of the problem.
  distributed-process: -O0
rebuild-ghc-options: true

docker:
  enable: false
  repo: quay.io/tweag/halon:latest
  registry-login: true
  # XXX To route around GHC bug #11042
  env:
  - M0_SRC_DIR=/mero
  - LD_LIBRARY_PATH=/mero/mero/.libs
  - USER=stack # for m0 script
  - TEST_LISTEN=127.0.0.1:8090

nix:
  enable: false
  packages: [ leveldb
            , libiconv
            , pcre
            ]

allow-different-user: true
