module HA.EventQueue.Types
    ( HAEvent(..)
    , UUID
    ) where

import Control.Distributed.Process (ProcessId)

import Data.Binary (Binary)
import Data.Function (on)
import Data.Typeable (Typeable)
import Data.UUID (UUID)

import GHC.Generics (Generic)

-- | An HA event. Generated by satellites.
data HAEvent a = HAEvent
    { eventId      :: {-# UNPACK #-} !UUID
    , eventPayload :: a
    , eventHops    :: [ProcessId]
    } deriving (Generic, Typeable)

instance Binary a => Binary (HAEvent a)

instance Eq (HAEvent a) where
    (==) = (==) `on` eventId

instance Ord (HAEvent a) where
    compare = compare `on` eventId
