# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, cep, distributedProcess, lens, mtl, networkTransport
, networkTransportTcp, time, binary, random, sodium, sodiumUtils, gloss, ...
}:

cabal.mkDerivation (self: {
  pname   = "cep-sodium";
  version = "0.1.0.0";
  sha256  = "TODO";
  src     = ./.;

  buildDepends = [ cep distributedProcess lens mtl networkTransport
    networkTransportTcp sodium sodiumUtils time binary
    random gloss ];

  meta = {
    description = "A Sodium FRP front-end to the cep library";
    license     = self.stdenv.lib.licenses.unfree;
    platforms   = self.ghc.meta.platforms;
  };
})
