FROM centos:centos7

# this fedora image starts without $HOME set right...
# fix that...
ENV HOME /root
ENV LANG en_US.UTF-8


RUN yum install -y yum-utils

WORKDIR /etc/yum.repos.d
# RUN curl -O https://copr.fedoraproject.org/coprs/petersen/ghc-7.8.4/repo/epel-7/petersen-ghc-7.8.4-epel-7.repo
RUN curl -O https://copr.fedoraproject.org/coprs/petersen/ghc-7.10.1/repo/epel-7/petersen-ghc-7.10.1-epel-7.repo
RUN yum-config-manager --disable petersen-ghc-7.10.1

# for leveldb
RUN yum install -y epel-release
RUN yum-config-manager --disable epel

# general build stuff
RUN yum install -y make git rpm-build chrpath dnf

# these are a restricted set of GHC packages
# from rawhide; the overall "ghc" package is not
# installed because it brings in a lot of libraries
# that we want our own version of.
# some ofthese are dependencies for ghc-Cabal-devel that
#  are not properly represented in the metadata.
RUN yum install -y --enablerepo=petersen-ghc-7.10.1 ghc-compiler ghc-array-devel ghc-binary-devel ghc-bytestring-devel ghc-containers-devel ghc-deepseq-devel ghc-template-haskell-devel ghc-pretty-devel ghc-directory-devel ghc-filepath-devel ghc-process-devel ghc-time-devel ghc-unix-devel ghc-old-locale-devel ghc-Cabal-devel ghc-transformers-devel

RUN yum install -y python3-requests python-requests python-dnf python-kickstart

# this is needed as a dependency for the Haskell
# zlib cabal package, which needs to be manually
# expressed here because the cabal packaging does
# not express it
RUN yum install -y zlib-devel

# this is needed for leveldb haskell package
RUN yum install -y --enablerepo=epel leveldb-devel

RUN mkdir -p /h

# for some of the subsequent steps, we need
# to ssh to places.
RUN mkdir    -p /root/.ssh

ADD id_rsa /root/.ssh/id_rsa
ADD known_hosts /root/.ssh/known_hosts
RUN chmod go-rwx /root/.ssh/id_rsa

ENV WORKDIR /h
ENV HALONSRC /h/halon

WORKDIR /h

# so now we have a recent cabal and cabal-rpm tool
# installed (not using RPM)

RUN git clone git@github.com:tweag/halon.git

WORKDIR /h/halon
RUN git checkout @@COMMIT@@
RUN git submodule update --init --recursive

WORKDIR /h/halon/docker/rpm
RUN ./bootstrap-build-tools.sh

# we're using ghc 7.8.4 but the halon repo is set for 7.8.3
# which has a slightly different base constraint.
# RUN sed -i 's/base ==4.7.0.1/base ==4.7.0.2/' /h/halon/cabal.config

# this is a version pin that comes from an ansi-terminal
# conflict that does not always show up (perhaps because
# of non-deterministic dependency build order)
# RUN echo "   , tasty ==0.10.0.3" >> /h/halon/cabal.config

RUN mkdir -p /root/rpmbuild/SOURCES
RUN mkdir -p /root/rpmbuild/SPECS
WORKDIR /root/rpmbuild/SPECS

# the packages neeed to be built in approximately
# this order

ADD build-with-cblrpm.sh /h/build-with-cblrpm.sh
RUN /h/build-with-cblrpm.sh

# by the time you reach here, you should have
# the SRPMs /root/rpmbuild/SRPM.
# They can be built with mockchain, in
# order of creation time.

