version: 2

jobs:
  build:
    working_directory: ~/halon
    docker:
      - image: seagate/halon-devel:7.4
        auth:
          username: seagateci
          password: $SSG_DOCKERHUB_PASSWD
      - image: rabbitmq:3
    steps:
      - checkout

      - run:
          name: Halon revision
          command: git --no-pager log -1

      - run:
          name: Checking-out latest Mero master
          working_directory: ~/
          command: git clone --recursive ${CIRCLE_REPOSITORY_URL%/*}/mero.git

      - run:
          name: Mero revision
          working_directory: ~/mero
          command: |
              git describe
              git --no-pager log -1

      - run:
          name: Building Mero master
          working_directory: ~/mero
          command: |
              ./autogen.sh
              ./configure --with-linux=/lib/modules/$(yum list installed kernel | tail -n1 | awk '{ print $2 }').x86_64/build
              make -j8

      - run:
          name: Building Halon
          no_output_timeout: 45m
          # the second `make` invocation is needed as a workaround for the
          # following build error of 'regex-tdfa' package:
          #
          #   --  While building custom Setup.hs for package regex-tdfa-1.2.2 using:
          #   /root/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.2.0 build --ghc-options " -ddump-hi -ddump-to-file"
          #   Process exited with code: ExitFailure (-9) (THIS MAY INDICATE OUT OF MEMORY)
          #   Logs have been written to: /root/halon/.stack-work/logs/regex-tdfa-1.2.2.log
          #
          # TODO: investigate the root cause and implement a proper solution
          command: ./scripts/h0 make || ./scripts/h0 make

      - run:
          name: Running Halon unit tests
          command: ./scripts/h0 test

workflows:
  version: 2
  precommit:
    jobs:
      - build:
          context: ssg-auth
