FROM centos:centos7
MAINTAINER ben.clifford@tweag.io

ENV HOME /root
# because otherwise HOME points to / but ~root points to /root

ENV LANG en_GB.UTF-8

# install required softare from repository
# autoconf is need while the network package is vendored but we defer it until layer 2
RUN yum install --assumeyes epel-release \
    && yum install --assumeyes bzip2 tar zlib-devel git gmp-devel make perl gcc pcre-devel libgenders-devel net-tools leveldb-devel


# install GHC from source
RUN curl -O https://downloads.haskell.org/~ghc/@@GHCVERSION@@/ghc-@@GHCVERSION@@-x86_64-unknown-linux-deb7.tar.bz2 \
    && bunzip2 ghc-@@GHCVERSION@@-x86_64-unknown-linux-deb7.tar.bz2  \
    && tar xf ghc-@@GHCVERSION@@-x86_64-unknown-linux-deb7.tar       \
    && cd ./ghc-@@GHCVERSION@@ && ./configure && make install && cd .. \
    && rm -rf ghc-@@GHCVERSION@@ \
              ghc-@@GHCVERSION@@-x86_64-unknown-linux-deb7.tar \
              ghc-@@GHCVERSION@@-x86_64-unknown-linux-deb7.tar.bz2

# install cabal install
RUN curl -O https://www.haskell.org/cabal/release/cabal-install-@@CABALVERSION@@/cabal-install-@@CABALVERSION@@.tar.gz \
    && tar xzf cabal-install-@@CABALVERSION@@.tar.gz \
    && cd /cabal-install-@@CABALVERSION@@ && ./bootstrap.sh && cd .. \
    && rm -rf /cabal-install-@@CABALVERSION@@ cabal-install-@@CABALVERSION@@.tar.gz \
    && ln -vs /root/.cabal/bin/cabal /usr/local/bin/cabal
