#!/usr/bin/env bash
. $H0_SRC_DIR/st/common

SERIAL='STOBAD002'
DRIVE_SELECT_OPTS="--slot-enclosure ENC#0 --serial $SERIAL --slot-index 2"

export M0_CLUSTER=  # single-node
$H0 init
cluster_bootstrap

# XXX Use c0cp instead of dd (i.e., clovis instead of m0t1fs).
$SUDO dd if=/dev/zero of=/mnt/m0t1fs/fedcba98:76543210 bs=32k count=100

# "Fail" a drive.
hctl mero drive update-presence $DRIVE_SELECT_OPTS
wait_for_drive_state 'SDSRepaired' $SERIAL

hctl mero vars set --disable-smart-check True
# "Replace" the drive.
hctl mero drive update-presence $DRIVE_SELECT_OPTS --is-powered --is-installed
hctl mero drive update-status $DRIVE_SELECT_OPTS --status OK
wait_for_drive_state 'SDSOnline' $SERIAL

hctl mero stop
$H0 fini

report_and_exit ${0##*/} $?
