FROM tweag/haskell-env-on-centos-7:@@BASEVERSION@@
MAINTAINER ben.clifford@tweag.io

# update cabal database to get newest deps
RUN cabal update

# this will need github permissions...
RUN mkdir /root/.ssh
ADD id_rsa /root/.ssh/
ADD known_hosts /root/.ssh/

# needed while the network package is vendored
RUN yum install --assumeyes autoconf

WORKDIR /
RUN git clone git@github.com:tweag/halon.git
WORKDIR /halon
RUN git checkout @@COMMIT@@

# update and install the dependencies
# into sandbox
RUN git submodule update --init --recursive
RUN make dep

