# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, time, sodium, unboundedDelays }:

cabal.mkDerivation (self: {
  pname = "sodium-utils";
  version = "0.1.0.0";
  sha256 = "TODO";
  src = ./.;
  buildDepends = [ time sodium unboundedDelays ];
  meta = {
    description = "Utilities for the Sodium FRP library";
    license = self.stdenv.lib.licenses.unfree;
    platforms = self.ghc.meta.platforms;
  };
})
