#!/usr/bin/env bash
set -eu -o pipefail

# Local version of halonctl. This script attempts to parse sensible
# values for '-l' and '-a' parameters from the `/etc/sysconfig/halond`
# file to simplify calling halonctl. Thus it always uses the local
# `halond` instance as an argument to `-a`.
#
# For more fine-grained control, please call `halonctl` directly.

HALOND_CONF=/etc/sysconfig/halond

die() { echo "$@" >&2; exit 1; }

if [ "$*" = '--version' ]; then
    exec halonctl --version
fi

if [ -e "$HALOND_CONF" ]; then
    . "$HALOND_CONF"
fi

[ -n "$HALOND_LISTEN" ] ||
    die "HALOND_LISTEN variable not set; please export or add to $HALOND_CONF"

IFS=':' read -ra ADDR <<< "$HALOND_LISTEN"
IP=${ADDR[0]}
[ -n "$IP" ] || die "Cannot determine IP ($IP) from $HALOND_LISTEN"
HALONCTL_LISTEN="$IP:0"

[ -n "$HALOND_STATION_OPTIONS" ] &&
    export HALOND_STATION_OPTIONS

exec halonctl -l "$HALONCTL_LISTEN" -a "$HALOND_LISTEN" "$@"
