#!/bin/bash

[ -z ${GENDERS} ] && echo >&2 "No genders file specified" && exit 1

pushd `dirname $0` > /dev/null
SCRIPTPATH=`pwd -P`
popd > /dev/null

source $SCRIPTPATH/query.inc

case $1 in
  dummyService) 
     cd $SCRIPTPATH/../../network-transport-rpc/rpclite
     make -e "RPC_ADDR=$2" run-dummyService
     ;;
  mym0dendpoint)
     mym0dendpoint
     echo "$ENDPOINT"
     ;;
  m0d) exec m0d -f ${GENDERS} -g
     ;;
  m0ctl) exec m0ctl -f ${GENDERS} -y query-all -r 2
     ;;
  nodes)
     ARG=$2
     [ -z "$ARG" ] && echo "[]" && exit 1
     RET="$(query ${ARG} h)"
     echo "$RET"
     ;;
  attr)
     ARG=$2
     ATTR=$3
     [ -z "$ARG" ] && echo "" && exit 1
     [ -z "$ATTR" ] && echo "" && exit 1
     RET="$(query ${ARG} ${ATTR})"
     echo "$RET"
     ;;
  *) echo >&2 "Unknown parameter"
     ;;
esac
