#!/bin/bash

HOSTNAME="$(hostname -s)"
IFACE="$(sudo lctl list_nids | head -1)"

read IFACEADDR IFACETYPE <<<$(IFS="@"; echo $IFACE)

TCPIFACE="$(host ${HOSTNAME})"
TCPIFACEADDR="${TCPIFACE##* }"

UUID="$(uuidgen)"

echo "${HOSTNAME}  m0_lnet_kernel_portal=34"
echo "${HOSTNAME}  m0_lnet_m0d_portal=35"
echo "${HOSTNAME}  m0_lnet_client_portal=36"
echo "${HOSTNAME}  m0_lnet_if=${IFACETYPE},m0_lnet_pid=12345"
echo "${HOSTNAME}  m0_lnet_host=${IFACEADDR}"
echo "${HOSTNAME}  m0_tcp_host=${TCPIFACEADDR}"
echo "${HOSTNAME}  m0_var=/var/mero"
echo "${HOSTNAME}  m0_max_rpc_msg=163840"
echo "${HOSTNAME}  m0_min_recv_q=2"
echo "${HOSTNAME}  m0_uuid=${UUID}"
echo "${HOSTNAME}  m0_s_addb=-A;/var/mero/addb-stobs"
echo "${HOSTNAME}  m0_s_ioservice=-T;linux;-S;/var/mero/stobs;-w;10"
echo "${HOSTNAME}  m0_s_mdservice=-p;-D;/var/mero/db"
echo "${HOSTNAME}  m0_u_addb=$(uuidgen)"
echo "${HOSTNAME}  m0_u_ioservice=$(uuidgen)"
echo "${HOSTNAME}  m0_u_mdservice=$(uuidgen)"
echo "${HOSTNAME}  m0_all"
echo "${HOSTNAME}  m0_station"
