#!/bin/bash -e

IP=127.0.0.1

TS=$IP:9010
HCTL=$IP:9001

cd /tmp
rm -rf halon-persistence

if [ -z "$HALON_ROOT" ]; then
  export HALON_ROOT=/usr/bin
fi

HALONCTL="$HALON_ROOT/halonctl"

$HALONCTL -l $HCTL cluster load -v -f $1 -r $2

cd /tmp
rm -rf halon-persistence
