#!/usr/bin/env bash
set -eu -o pipefail
# set -x
export PS4='+ [${FUNCNAME[0]:+${FUNCNAME[0]}:}${LINENO}] '

PROG=${0##*/}

usage() {
    cat <<EOF
Usage: $PROG [-h | --help]
Stop Halon processes, delete persisted data, trace and log files.

Option:
    -h, --help    Show this help and exit.
EOF
}

die() { echo "$*" >&2; exit 1; }

_kill() { killall -v -KILL "$@" 2>/dev/null || true; }

case ${1:-} in
    -h|--help) usage; exit 0;;
    '') :;;
    *) die "Invalid argument. Type \`$PROG --help' for usage.";;
esac

(($(id -u) == 0)) || die 'Must be run by superuser'

pids=$(pidof halond || true)

_kill halonctl
systemctl status halond &>/dev/null && systemctl stop halond || _kill halond

rm -rfv /var/lib/halon/halon-persistence/

for pid in $pids; do
    rm -fv {,/var/lib/halon/}m0trace.$pid
done

rm -fv /var/log/halon.{decision,trace}.log
