#!/usr/bin/env bash
set -eu -o pipefail

DEBUG_MODE=0  # Output format: 0 - dot; 1 - org mode.

usage() {
    cat <<EOF
Usage: ${0##*/} [DIR]
       ${0##*/} {-d|--debug} [DIR]
       ${0##*/} {-h|--help}

Generate Halon resource graph schema in DOT format.

Optional parameter \`DIR' specifies the path to Halon sources directory,
which resources information will be read from. \`DIR' defaults to current
directory.

When started in debug mode (\`--debug'), the script outputs "raw" resource
information in org-mode format.

Example:
    dot -Tpng -o /tmp/rg.png <(scripts/${0##*/}) && open /tmp/rg.png
EOF
}

die() { echo "$@" >&2; exit 1; }

## contains abc b -> 1
## contains abc d -> 0
contains() {
    local str="$1" pat="$2"
    [ "${str/$pat/}" = "$str" ] && return 1 || return 0
}

encode_cardinality() {
    awk '
NF == 5 {
    print $1, $3, $5 ($4 == "Unbounded" ? "*" : "")
    next
}
NF != 3 {
    print "Unexpected number of fields:", NF > "/dev/stderr"
    print "Input:", $0 > "/dev/stderr"
    exit 1
}
{ print }
'
}

RESOURCE_DIRS='halon/src/lib mero-halon/src/lib'

edit_prefixes() {
    local src rel dst
    case "$1" in
        mero-halon/src/lib/HA/Resources/Mero.hs)
            while read -r src rel dst; do
                if contains "$src" .; then
                    src="${src/#R./}"
                else
                    src="M0.$src"
                fi
                rel="${rel/#R./}"
                if contains "$dst" .; then
                    dst="${dst/#R./}"
                else
                    dst="M0.$dst"
                fi
                echo $src $rel $dst
            done;;
        mero-halon/src/lib/HA/Resources/RC.hs| \
        mero-halon/src/lib/HA/Services/Mero/RC/Resources.hs)
            while read -r src rel dst; do
                src="$(echo $src | sed -E 's/^RC?\.//')"
                rel="$(echo $rel | sed -E 's/^RC?\.//')"
                dst="$(echo $dst | sed -E 's/^RC?\.//')"
                echo $src $rel $dst
            done;;
        mero-halon/src/lib/HA/Resources/Castor/Initial/Old.hs)
            while read -r src rel dst; do
                src="${src/#C./}"
                rel="${rel/#R./}"
                echo $src $rel $dst
            done;;
        *)
            cat;;
    esac
}

to_dot() {
    sort -u | awk '
function dot(s, extra) {
    split(s, a)
    printf("    \"%s\" -> \"%s\" [label=\"%s\"%s];\n", a[1], a[3], a[2], extra)
}

function flush() {
    if (prev) {
        dot(prev, "")
        prev = ""
    }
}

BEGIN { print "digraph RG {" }
/\*$/ {
    cur = substr($0, 1, length-1)
    if (prev == cur)
        prev = ""
    else
        flush()
    dot(cur, ", arrowhead=\"onormal\"")
    next
}
{ flush(); prev = $0 }
END {
    flush()
    print "}"
}
'
}

## -------------------------------------------------------------------
## main()

case "${1:-}" in
    -d|--debug) shift; DEBUG_MODE=1;;
    -h|--help) usage; exit;;
esac
[ -z "${1:-}" ] || cd "$1"
git rev-parse --show-toplevel >/dev/null  # fail if PWD is not a git repository
for d in $RESOURCE_DIRS; do
    [ -d "$d" ] || die "No Halon sources found in $PWD"
done

git grep -l "(''" -- $RESOURCE_DIRS | while read -r f; do
    if [ $DEBUG_MODE -eq 1 ]; then
        echo "* $f"
        sed -n 's/^import qualified.*Resources.* as /# &/p' $f
    fi
    sed -n "s/.*(''//p" $f | tr -d ",()[]'" | tr -s ' ' |
        sed -Ee 's/^ +//' -e 's/ +$//' |
        if [ $DEBUG_MODE -eq 1 ]; then
            cat
        else
            encode_cardinality | edit_prefixes $f
        fi
done |
    if [ $DEBUG_MODE -eq 1 ]; then
        cat     # org-mode output
    else
        to_dot  # dot output
    fi
