#!/bin/bash
set -m

## This script will read the genders file (pointed to in the
## GENDERS variable) and use it to deploy HA node agents
## and stations. The actual execution of the HA binaries
## is taken care of by the scripts/ha script, which is called
## by this script. Since scripts/ha reads the local genders file,
## this script assumes that identical genders files have already
## been disseminated to all nodes.

# find absolute path of this script
pushd `dirname $0` > /dev/null
SCRIPTPATH=`pwd -P`
popd > /dev/null

HA=$SCRIPTPATH/ha

function help
{
  echo "Syntax: "
  echo "  $(basename "$0") [start|stop] config_file"
  echo " "  
  echo "The configuration is in the genders format. If not specified,"
  echo "use the default /etc/mero/genders."  
  echo ""
  echo "start:"
  echo "A node agent will be started on each host (m0_all) and the"
  echo "station will be started on hosts so marked (m0_station)."
  echo ""
  echo "stop:"
  echo "Node agents will be stoped on all hosts."
  echo ""
  exit 1
}

source $SCRIPTPATH/query.inc

CMD="$1"
CONFIG="${2:-"/etc/mero/genders"}"
GENDERS=${CONFIG}

function start
{
  echo "starting node agents ... "
  sudo pdsh -R ssh -w "$(query m0_all c)" "cd `pwd`; PATH=$PATH $HA node-agent" &
  sleep 40
  echo "starting station ... "
  sudo pdsh -R ssh -w "$(query m0_station c)" "cd `pwd`; PATH=$PATH GENDERS=${CONFIG} $HA station"
  fg 1 > /dev/null
}

[ -z "${CMD:-}" -o -z "${CONFIG:-}" ] && help
[ ! -f "$CONFIG" ] && echo "Could not find configuration file: ${CONFIG}" && exit 1

case ${CMD} in
start)
  start
  ;;
stop)
  echo "stoping node agents ... "
  sudo pdsh -R ssh -w "$(query m0_all c)" "killall ha-node-agent"
  ;;
*)
  help
 ;;
esac
