#!/bin/bash

source docker/functions.sh

DEPVERSION=$(generate-dep-version)

export COMMIT=$(git rev-parse HEAD)

echo COMMIT = $COMMIT

cat docker/3-halon/Dockerfile.template \
  | sed "s/@@DEPVERSION@@/${DEPVERSION}/g" \
  | sed "s/@@COMMIT@@/${COMMIT}/g" > docker/3-halon/Dockerfile
docker build -t tweag/halon docker/3-halon/
