#!/bin/bash

source docker/functions.sh

DEPVERSION=$(generate-dep-version)

export COMMIT=$(git rev-parse HEAD)

echo COMMIT = $COMMIT

cat docker/3-halon/Dockerfile.in \
  | sed "s/@@DEPVERSION@@/${DEPVERSION}/g" \
  | sed "s/@@COMMIT@@/${COMMIT}/g" > docker/3-halon/Dockerfile

docker build -t tweag/halon docker/3-halon/ || exit 1

echo Running build container

ContainerID=$(docker run -d --name=halon-build tweag/halon docker/3-halon/build-with-artifacts)

docker attach $ContainerID

BuildRC=$(docker wait $ContainerID)

echo Build exit code $BuildRC

echo "Copying log files from halon build container to CIRCLE_ARTIFACTS ( = ${CIRCLE_ARTIFACTS} )"
docker cp halon-build:/halon/artifacts ${CIRCLE_ARTIFACTS}

exit $BuildRC
