FROM tweag/halon-deps:@@DEPVERSION@@
MAINTAINER ben.clifford@tweag.io

ADD id_rsa /root/.ssh/
ADD known_hosts /root/.ssh/

WORKDIR /halon
RUN git fetch
RUN git checkout @@COMMIT@@

# build halon, which will also run the tests,
# hopefully.

ENV CABAL_FLAGS --flag="maintainer"
RUN make

