FROM tweag/halon-deps:@@DEPVERSION@@
MAINTAINER ben.clifford@tweag.io

ADD id_rsa /root/.ssh/
ADD tweagremote_keypair /root/.ssh/
ADD known_hosts /root/.ssh/
RUN echo IdentityFile /root/.ssh/tweagremote_keypair >> /root/.ssh/config
RUN echo IdentityFile /root/.ssh/id_rsa >> /root/.ssh/config

RUN chmod go-rwx /root/.ssh/id_rsa
RUN chmod go-rwx /root/.ssh/tweagremote_keypair

WORKDIR /halon
RUN git fetch
RUN git checkout @@COMMIT@@
RUN git submodule update --init --recursive

# build halon, which will also run the tests,
# hopefully.

ENV CABAL_FLAGS --flag="maintainer" --flag="distributed-tests"
ENV DC_PROVIDER=docker
# RUN docker/3-halon/build-with-artifacts
